services:
  sentinel-dashboard:
    build: .
    container_name: sentinel_dashboard_container
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
    command: streamlit run app_dashboard.py --server.address=0.0.0.0
